--liquibase formatted sql

--changeset Ilya:1
--comment create order table
CREATE TABLE "order"
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    goods_name VARCHAR(160)                            NOT NULL,
    category   VARCHAR(255)                            NOT NULL,
    client_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #1', 0, 1);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #2', 1, 1);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #3', 2, 1);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #1', 0, 2);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #3', 1, 2);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #4', 2, 2);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #1', 0, 3);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #5', 1, 3);
INSERT INTO "order"(goods_name, category, client_id) VALUES ('Goods #6', 2, 3);
--rollback truncate table order;